bubble-dev/_

- packages/math-playground/src/index.ts
- packages/math-playground/test/index.ts
Introducing:
```typescript
import { cost, costDerivative, powerRuleDerivative } from 'math-playground'
cost(1)(0.5) // 0.25
costDerivative(1)(0.5) // -1
powerRuleDerivative(2)(3) // 6
```
> More math functions

- packages/math-playground/src/index.ts
- packages/math-playground/test/index.ts
```typescript
import { denormalizeMatrix, normalizeMatrix } from 'math-playground'
descentStep(0.3)(40) // -12
denormalizeLinear(100)(0.75) // 75
normalizeLinear(100)(50) // 0.5
normalizeMatrix(400)([[40, 80], [160, 200]]) // [[0.1, 0.2], [0.4, 0.5]]
denormalizeMatrix(400)([[0.1, 0.2], [0.4, 0.5]]) // [[40, 80], [160, 200]]
> More auxiliary math functions

- packages/primitives/image/license.md
- packages/primitives/image/package.json
- packages/primitives/image/readme.md
- packages/primitives/image/src/Root.native.tsx
- packages/primitives/image/src/Root.web.tsx
- packages/primitives/image/src/index.native.ts
- packages/primitives/image/src/index.web.ts
- packages/primitives/image/src/types.ts
- packages/stili/src/index.native.ts
on the quest of adding a new primitive!
should i add tests? is there any good reason to use `{ FC } from 'react'`? when to use `import { normalizeStyle } from 'stili'`?
anyway.... a PR is made!
> Add image primitive

- packages/refun/readme.md
- packages/refun/src/map-debounced-handler.ts
> Refun docs

- readme.md
> 📝 explain metarepo

- packages/primitives/checkbox/readme.md
> checkbox readMe onToggle

- packages/rebox/web/src/build-web/get-config.ts
- packages/rebox/web/src/run-web/get-config.ts
> 🐞 rebox/web: fix images and videos loader

- packages/primitives/table/license.md
- packages/primitives/table/package.json
- packages/primitives/table/readme.md
- packages/primitives/table/src/Table.tsx
- packages/primitives/table/src/TableBody.tsx
- packages/primitives/table/src/TableBodyCell.tsx
- packages/primitives/table/src/TableHead.tsx
- packages/primitives/table/src/TableHeadCell.tsx
- packages/primitives/table/src/TableRow.tsx
- packages/primitives/table/src/index.web.ts
- packages/primitives/table/src/types.ts
> 🐣 primitives/table: init table

- package.json
- packages/bsc/license.md
- packages/bsc/package.json
- packages/bsc/readme.md
- packages/bsc/src/index.ts
- packages/bsc/test/index.ts
https://github.com/deepsweet/bsc
> 🐣 bsc: transfer package

- packages/primitives/table/src/TableHeadCell.tsx
Add `width` prop to TableHeadCell to be able to set column width.
> 🌱 primitives/table: add 'width' prop to TableHeadCell

- package.json
- packages/makethen/license.md
- packages/makethen/package.json
- packages/makethen/readme.md
- packages/makethen/src/index.ts
- packages/makethen/test/index.ts
https://github.com/deepsweet/makethen
> 📦 makethen: transfer package

- packages/primitives/image/src/types.ts
- packages/themeables/image/meta.tsx
- packages/themeables/image/src/types.ts
Move style related props (height, width, borderRadius) from @primitive/image to @themeable/image.
> 🐞 primitives/image, themeables/image: move style related props from primitive to themeable for image

- packages/primitives/image/package.json
- packages/themeables/image/package.json
update package.json for image primitive and themeable
> 🐞 primitives/image, themeables/image: update package.json for image primitive and themeable

- packages/bubble-dev/start-preset/src/plugins/with-chromium.ts
- packages/x-ray/chrome-perf-snapshots/package.json
- packages/x-ray/chrome-screenshots/package.json
- packages/xrom/src/index.ts
- yarn.lock
> ♻️ update `puppeteer-core` to v2 and Chromium to v79

- packages/bubble-dev/start-preset/src/build.ts
- packages/start/cli/package.json
- packages/start/cli/src/index.js
- packages/start/cli/src/lib.ts
> 🐞 bubble-dev/start-preset: fix building packages with CLI

- package.json
- packages/start/plugin-lib-jest/package.json
- packages/start/plugin-lib-jest/readme.md
- packages/start/plugin-lib-jest/src/index.ts
- yarn.lock
> ♻️ bump deps

- package.json
- packages/x-ray/chrome-perf-snapshots/src/check-snapshots.ts
- packages/x-ray/chrome-perf-snapshots/src/run-server.ts
- packages/x-ray/common-utils/src/types.ts
- packages/x-ray/native-screenshots/src/run-screenshots-server.ts
- packages/x-ray/screenshot-utils/src/run-screenshots.ts
- packages/x-ray/screenshot-utils/src/run-server.ts
- packages/x-ray/snapshots/src/run-server.ts
- packages/x-ray/snapshots/src/run-snapshots.ts
- packages/x-ray/ui/package.json
- packages/x-ray/ui/src/components/Popup.tsx
- packages/x-ray/ui/src/components/SourceCode/index.tsx
- packages/x-ray/web-mobile-screenshots/src/run-screenshots-server.ts
- tasks/index.ts
- tasks/x-ray-ui/fixtures/get.json
- tasks/x-ray-ui/fixtures/list.json
- tasks/x-ray-ui/index.tsx
- tasks/x-ray-ui/run-server.ts
- tasks/x-ray-ui/template.html
> 🐞 x-ray: handle cases without source code

- package.json
- packages/bubble-dev/start-preset/package.json
- packages/lada/prefix/package.json
- packages/primitives/block-ref/package.json
- packages/primitives/block/package.json
- packages/primitives/button/package.json
- packages/primitives/checkbox/package.json
- packages/primitives/heading/package.json
- packages/primitives/image/package.json
- packages/primitives/input/package.json
- packages/primitives/layout/package.json
- packages/primitives/link/package.json
- packages/primitives/pointer/package.json
- packages/primitives/root/package.json
- packages/primitives/select/package.json
- packages/primitives/size/package.json
- packages/primitives/table/package.json
- packages/primitives/text/package.json
- packages/primitives/transform/package.json
- packages/primitives/view/package.json
- packages/sandbox/ui/package.json
- packages/stili/package.json
- yarn.lock
closes #350 
closes #351 
closes #354
> ♻️ upgrade deps

- packages/primitives/link/src/Root.native.tsx
- packages/primitives/link/src/types.ts
so basically when using 'Text' tag for native it is a pain to use it for anything else but text, so if you wanna use an icon as a link its becoming an issue, this small PR trying to change it, one step at a time
> Native link touchable

- packages/primitives/spacer/meta.tsx
- packages/primitives/spacer/package.json
- packages/primitives/spacer/src/index.tsx
- tasks/sandbox/components/index.native.ts
- tasks/sandbox/components/index.ts
I added `Spacer` to sandbox and removed "position: absolute" from `Spacer`.
> 🐞 primitives/spacer: remove position absolute from spacer

- package.json
- packages/bubble-dev/eslint-config/package.json
- packages/bubble-dev/start-preset/package.json
- packages/sandbox/ui/src/components/component-controls/HandlerItem.tsx
- packages/themeables/background/meta.tsx
- packages/themeables/border/meta.tsx
- packages/themeables/core/meta.tsx
- packages/themeables/image/meta.tsx
- packages/themeables/layout/meta.tsx
- packages/themeables/spacer/meta.tsx
- packages/themeables/text/meta.tsx
- packages/themeables/vector-shape/meta.tsx
- yarn.lock
closes #272 
closes #364 
closes #374 
closes #381 
closes #382 
closes #405
> 🛠 ESLint v7

- packages/themeables/background/src/index.ts
- packages/themeables/border/src/index.ts
- packages/themeables/core/meta.tsx
- packages/themeables/core/src/index.ts
- packages/themeables/image/src/index.ts
- packages/themeables/layout/src/index.ts
- packages/themeables/spacer/src/index.ts
- packages/themeables/text-align/src/index.ts
- packages/themeables/text/src/index.ts
- packages/themeables/vector-shape/src/index.ts
- tasks/sandbox/components/index.ts
> 🚧 themeables/core: scaffolding of theme override

- packages/themeables/background/meta.tsx
- packages/themeables/background/src/index.ts
- packages/themeables/border/meta.tsx
- packages/themeables/border/src/index.ts
- packages/themeables/core/meta.tsx
- packages/themeables/core/src/index.ts
- packages/themeables/image/meta.tsx
- packages/themeables/image/src/index.ts
- packages/themeables/layout/meta.tsx
- packages/themeables/layout/src/index.ts
- packages/themeables/spacer/meta.tsx
- packages/themeables/spacer/src/index.ts
- packages/themeables/text-align/meta.tsx
- packages/themeables/text-align/src/index.ts
- packages/themeables/text/meta.tsx
- packages/themeables/text/src/index.ts
- packages/themeables/vector-shape/meta.tsx
- packages/themeables/vector-shape/src/index.ts
- tasks/sandbox/components/index.native.ts
- tasks/sandbox/components/index.ts
This is the most important part to review: https://github.com/bubble-dev/_/pull/454/commits/e020a79b48aed4f4c62ad0a6ec5f48c5f251afa7
> Rewrite themeables

- packages/stili/src/types.ts
need `listStyleType` style for list primitive
> 🐞 stili: add web list style to stili

- package.json
Same as: https://github.com/bubble-dev/_/pull/482
But needed one more dependency path to be able to run x-ray properly
> 🛠 fix xcode 12 for x-ray
